# syntax=docker/dockerfile:1.7
# ¿A dónde va tu dinero? MTY — static site served by unprivileged nginx.
# Base images are pinned by digest; Dependabot proposes updates.

# ---- Stage 1: build the web app (the JSON in data/public was already generated by the pipeline) ----
FROM node:22-alpine@sha256:0a7108bf6c7bf5de370ffb1a3ed6be93d405b43ff159f681a8d18c0e2bc2e402 AS web
WORKDIR /src/web
COPY web/package.json web/package-lock.json ./
RUN npm ci --ignore-scripts --no-audit --no-fund
COPY web/ ./
COPY data/public/ /src/data/public/
COPY data/raw/ /src/data/raw/
RUN npm run build

# ---- Stage 2: runtime ----
FROM nginxinc/nginx-unprivileged:1.30-alpine@sha256:ed04ec1ff34502c339ee5c3ae3f855442398edc1d05591e2b98981dcbbd20b1e
LABEL org.opencontainers.image.title="adonde-va-tu-dinero-mty" \
      org.opencontainers.image.description="¿A dónde va tu dinero? MTY — finanzas municipales de Monterrey, San Pedro y Santa Catarina" \
      org.opencontainers.image.source="https://github.com/javidr2243/k8s-custom-nginx" \
      org.opencontainers.image.licenses="MIT"

# Config and content are owned by root and only readable by the nginx user (uid 101).
COPY --chown=root:root --chmod=0644 nginx.conf /etc/nginx/nginx.conf
COPY --chown=root:root --chmod=0644 security-headers.conf /etc/nginx/security-headers.conf
COPY --from=web --chown=root:root /src/web/dist /usr/share/nginx/html

USER 101
EXPOSE 8080
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget -q -O /dev/null http://127.0.0.1:8080/healthz || exit 1
