// Types and loaders for the JSON generated by the pipeline (data/public/v1). Read only.

export type MunicipioId = 'monterrey' | 'san-pedro' | 'santa-catarina';
export const MUNICIPIOS: MunicipioId[] = ['monterrey', 'san-pedro', 'santa-catarina'];

export type Medida = 'aprobado' | 'ampliaciones' | 'modificado' | 'devengado' | 'pagado' | 'subejercicio';
export type Montos = Record<Medida, number | null>;

export interface Capitulo {
  clave: string;
  nombre: string;
  montos: Montos;
  conceptos: { nombre: string; montos: Montos }[];
}

export interface Dependencia {
  id: string;
  nombre: string;
  montos: Montos;
  notas?: string[];
}

export interface PeriodoEgresos {
  periodo: string;
  fecha_corte: string;
  fuente: string;
  total: Montos;
  capitulos: Capitulo[];
  dependencias: Dependencia[] | null;
  fuente_dependencias: string | null;
  motivo_sin_dependencias?: string;
  notas: string[];
}

export interface Faltante {
  periodo: string;
  motivo: string;
}

export interface Egresos {
  municipio: MunicipioId;
  unidad: string;
  nota_unidad: string;
  periodos: PeriodoEgresos[];
  faltantes: Faltante[];
}

export interface Rubro {
  id: string;
  nombre: string;
  montos: Record<'estimado' | 'ampliaciones' | 'modificado' | 'devengado' | 'recaudado', number | null>;
}

export interface Ingresos {
  municipio: MunicipioId;
  trimestral: {
    periodo: string;
    fecha_corte: string;
    fuente: string;
    total: Rubro['montos'];
    rubros: Rubro[];
  }[];
  motivo_sin_trimestral: string | null;
  anual: {
    anio: number;
    estatus: string;
    egresos_total: number | null;
    gasto_total: number | null;
    ingresos_total: number | null;
    egresos_capitulo: Record<string, number>;
    ingresos_rubro: Record<string, number>;
  }[];
  fuente_anual: string;
}

export interface Saldo {
  periodo: string;
  fecha: string;
  total: number;
  banca_multiple: number;
  banca_desarrollo: number;
  emisiones: number;
  otros: number;
  fuente: string;
}

export interface Credito {
  acreedor: string;
  tipo: string;
  fecha_contratacion: string;
  monto_original: number | null;
  saldo: number | null;
  saldo_fecha: string;
  plazo_dias: number | null;
  tasa: string;
  sobretasa: number | null;
  vencimiento: string;
  fuente_pago: string;
  destino: string;
}

export interface Alerta {
  evaluacion: string;
  resultado: number | null;
  etiqueta: string | null;
  indicadores: (number | null)[];
  nota: string;
  fuente: string;
}

export interface Deuda {
  municipio: MunicipioId;
  saldos: Saldo[];
  creditos: Credito[];
  fuente_creditos: string;
  nota_creditos: string;
  pagos_capitulo_9000: { periodo: string; montos: Montos | null; fuente: string }[];
  nota_pagos: string;
  anual_detalle: { anio: number; amortizacion: number; intereses: number; gastos: number; total: number }[];
  fuente_anual_detalle: string | null;
  alertas: Alerta[];
  nota_alertas: string;
}

export interface Contrato {
  numero: string;
  fecha: string | null;
  procedimiento: string;
  categoria: 'licitacion' | 'invitacion' | 'directa' | 'modificatorio' | 'otro';
  materia: string;
  descripcion: string;
  proveedor: string;
  tipo_persona: 'moral' | 'fisica' | 'reservada' | 'desconocido';
  rfc: string | null;
  /** Requesting area (who needed the purchase); falls back to the contracting office. */
  area: string;
  area_solicitante: string;
  area_contratante: string;
  /** Budget department linked from the requesting area (Monterrey only); null when unclear. */
  dependencia: string | null;
  monto: number | null;
  monto_sin_impuestos: number | null;
  monto_maximo: number | null;
  origen_recursos: string;
  lugar_obra: string;
  fuente: string;
}

export interface Contratos {
  municipio: MunicipioId;
  fuentes: string[];
  resumen: {
    contratos: number;
    con_monto: number;
    monto_total: number;
    proveedores: number;
    reservados: number;
    por_categoria: Record<string, { nombre: string; n: number; monto: number }>;
    proveedores_top: { proveedor: string; rfc: string | null; n: number; monto: number; porcentaje: number | null }[];
    concentracion_top10: number | null;
    fechas: [string | null, string | null];
    por_area: (GrupoContratos & { area: string })[];
    por_dependencia: Record<string, GrupoContratos & { nombre: string; proveedores: ProveedorMonto[]; contratos: ContratoBreve[]; fechas: [string | null, string | null] }>;
    dependencias_ligadas: { contratos: number; de: number; areas_sin_ligar: string[] };
  };
  senales: Senales;
  notas: string[];
  contratos: Contrato[];
}

export interface GrupoContratos {
  n: number;
  monto: number;
  /** Share of the amount awarded directly (without an open tender). */
  pct_directa: number | null;
}
export interface ProveedorMonto {
  proveedor: string;
  rfc: string | null;
  n: number;
  monto: number;
}
export type ContratoBreve = Pick<Contrato, 'numero' | 'fecha' | 'proveedor' | 'rfc' | 'monto' | 'descripcion' | 'area' | 'fuente'>;
/** Objective patterns worth a closer look (they do not indicate irregularities). */
export interface Senales {
  umbrales: { meses_empresa_joven: number; min_directas_repetidas: number };
  empresas_jovenes: (ContratoBreve & { constitucion: string; dias: number })[];
  empresa_mas_joven: (ContratoBreve & { constitucion: string; dias: number }) | null;
  directas_repetidas: { proveedor: string; rfc: string | null; n: number; con_monto: number; monto: number | null; fechas: [string | null, string | null]; fuente: string }[];
  mayores_directas: ContratoBreve[];
  modificatorios: { n: number; monto: number; mayores: ContratoBreve[] };
}

export interface Municipio {
  id: MunicipioId;
  nombre: string;
  cvegeo: string;
  poblacion: number;
  fuente_poblacion: string;
  ultimo_periodo: string | null;
  detalle: { capitulos: boolean; dependencias: boolean; ingresos_trimestrales: boolean };
}

export interface Fuente {
  titulo: string;
  emisor: string;
  municipio: MunicipioId | null;
  periodo: string | null;
  url: string;
  pagina: string;
  formato: string;
  archivo: string;
  /** Archived copy served by the site; null when the original contains personal data (see sin_copia). */
  copia: string | null;
  sin_copia: string | null;
  extracto: boolean;
  sha256_original: string | null;
  bytes: number | null;
  sha256: string | null;
  publicado: string | null;
  descargado: string | null;
}

export interface Validacion {
  chequeos: {
    id: string;
    descripcion: string;
    revisados: number;
    aprobados: number;
    fallas: { fuente: string | null; municipio: MunicipioId | null; detalle: string }[];
  }[];
  advertencias: { mensaje: string; fuente: string | null; municipio: MunicipioId | null }[];
  nota: string;
}

export interface Comparativo {
  anios: number[];
  fuente: string;
  fuente_poblacion: string;
  metodo: string;
  municipios: Record<
    MunicipioId,
    {
      poblacion: number;
      anual: {
        anio: number;
        estatus: string;
        gasto_total: number | null;
        gasto_por_habitante: number | null;
        capitulos: Record<string, number>;
      }[];
    }
  >;
}

export interface Movimiento {
  fecha: string | null;
  municipio: MunicipioId;
  tipo: 'periodo' | 'modificacion' | 'deuda' | 'alerta' | 'contrato';
  titulo: string;
  detalle: string;
  monto: number | null;
  cambio: number | null;
  fuente: string;
}

export interface Meta {
  version_datos: number;
  version_pipeline: string;
  datos_al: string | null;
  periodo_mas_reciente: string;
  periodo_inicial: string;
  municipios: Record<MunicipioId, string | null>;
  unidad: string;
}

// "/data/v1/" on the site; relative in preview builds (see MEMORIA in router.svelte.ts).
const BASE = `${import.meta.env.BASE_URL}data/v1/`;
const cache = new Map<string, Promise<unknown>>();

export function load<T>(path: string): Promise<T> {
  let p = cache.get(path);
  if (!p) {
    p = fetch(BASE + path, { headers: { Accept: 'application/json' } }).then((r) => {
      if (!r.ok) throw new Error(`No se pudo cargar ${path} (HTTP ${r.status})`);
      return r.json();
    });
    p.catch(() => cache.delete(path));
    cache.set(path, p);
  }
  return p as Promise<T>;
}

export const api = {
  meta: () => load<Meta>('meta.json'),
  municipios: () => load<{ municipios: Municipio[] }>('municipios.json').then((d) => d.municipios),
  fuentes: () => load<{ fuentes: Record<string, Fuente> }>('fuentes.json').then((d) => d.fuentes),
  egresos: (m: MunicipioId) => load<Egresos>(`egresos/${m}.json`),
  ingresos: (m: MunicipioId) => load<Ingresos>(`ingresos/${m}.json`),
  deuda: (m: MunicipioId) => load<Deuda>(`deuda/${m}.json`),
  contratos: (m: MunicipioId) => load<Contratos>(`contratos/${m}.json`),
  comparativo: () => load<Comparativo>('comparativo.json'),
  movimientos: () => load<{ movimientos: Movimiento[] }>('movimientos.json').then((d) => d.movimientos),
  validacion: () => load<Validacion>('validacion.json'),
};

export const NOMBRE: Record<MunicipioId, string> = {
  monterrey: 'Monterrey',
  'san-pedro': 'San Pedro Garza García',
  'santa-catarina': 'Santa Catarina',
};

export const NOMBRE_CORTO: Record<MunicipioId, string> = {
  monterrey: 'Monterrey',
  'san-pedro': 'San Pedro',
  'santa-catarina': 'Santa Catarina',
};

export function esMunicipio(x: string | null | undefined): x is MunicipioId {
  return x === 'monterrey' || x === 'san-pedro' || x === 'santa-catarina';
}
